from typing import Dict, List, Optional
import re

from langchain_core.documents import Document


# ============================================================
# Citation helpers
# ============================================================

def get_document_citation(
    document: Document,
) -> str:
    """
    Return the canonical citation attached to a document.
    """

    if not isinstance(
        document,
        Document,
    ):
        raise TypeError(
            "document must be a LangChain Document"
        )

    metadata = (
        document.metadata
        or {}
    )

    citation = metadata.get(
        "citation"
    )

    if citation:
        return str(
            citation
        ).strip()

    source = metadata.get(
        "source",
        "Unknown source",
    )

    page = metadata.get(
        "page_number",
        "Unknown page",
    )

    return (
        f"{source} — Page {page}"
    )


def build_citation_map(
    documents: List[Document],
) -> Dict[int, str]:
    """
    Build a stable evidence-number → citation map.

    Example:
        [Evidence 1] -> source.pdf — Page 12
        [Evidence 2] -> guideline.pdf — Page 65
    """

    if not isinstance(
        documents,
        list,
    ):
        raise TypeError(
            "documents must be a list"
        )

    citation_map = {}

    evidence_index = 1

    for document in documents:

        if not isinstance(
            document,
            Document,
        ):
            continue

        citation = (
            get_document_citation(
                document
            )
        )

        citation_map[
            evidence_index
        ] = citation

        evidence_index += 1

    return citation_map


# ============================================================
# Citation rendering
# ============================================================

def render_citation(
    evidence_number: int,
    citation_map: Dict[int, str],
) -> str:
    """
    Render one citation safely.

    Returns empty string when the evidence number
    does not exist.
    """

    if evidence_number not in citation_map:
        return ""

    return (
        f"[{evidence_number}] "
        f"{citation_map[evidence_number]}"
    )


def render_citations(
    evidence_numbers: List[int],
    citation_map: Dict[int, str],
) -> str:
    """
    Render multiple citations.
    """

    citations = []

    seen = set()

    for number in evidence_numbers:

        if number in seen:
            continue

        citation = render_citation(
            number,
            citation_map,
        )

        if citation:
            citations.append(
                citation
            )

        seen.add(
            number
        )

    return "; ".join(
        citations
    )


# ============================================================
# Citation extraction from generated answer
# ============================================================

def extract_evidence_numbers(
    text: str,
) -> List[int]:
    """
    Extract [Evidence N] or [N] references from an LLM answer.

    Only numbers are returned; they must later be validated
    against the actual citation map.
    """

    if not isinstance(
        text,
        str,
    ):
        raise TypeError(
            "text must be a string"
        )

    numbers = []

    # Preferred format:
    # [Evidence 1]
    evidence_matches = re.findall(
        r"\[\s*Evidence\s+(\d+)\s*\]",
        text,
        flags=re.IGNORECASE,
    )

    for value in evidence_matches:

        number = int(
            value
        )

        if number not in numbers:
            numbers.append(
                number
            )

    # Also support compact:
    # [1]
    compact_matches = re.findall(
        r"(?<!Evidence\s)\[\s*(\d+)\s*\]",
        text,
        flags=re.IGNORECASE,
    )

    for value in compact_matches:

        number = int(
            value
        )

        if number not in numbers:
            numbers.append(
                number
            )

    return numbers


# ============================================================
# Citation validation
# ============================================================

def validate_citations(
    answer: str,
    citation_map: Dict[int, str],
) -> Dict:
    """
    Validate that every cited evidence number exists.

    This does NOT trust citation text generated by the LLM.
    """

    evidence_numbers = (
        extract_evidence_numbers(
            answer
        )
    )

    valid = []
    invalid = []

    for number in evidence_numbers:

        if number in citation_map:
            valid.append(
                number
            )
        else:
            invalid.append(
                number
            )

    return {
        "valid": len(invalid) == 0,
        "valid_evidence_numbers": valid,
        "invalid_evidence_numbers": invalid,
    }


# ============================================================
# Deterministic citation block
# ============================================================

def build_citation_block(
    documents: List[Document],
) -> str:
    """
    Build a citation block from actual retrieved documents.

    This is deterministic and independent of the LLM.
    """

    citation_map = build_citation_map(
        documents
    )

    if not citation_map:
        return (
            "No verified citations available."
        )

    lines = [
        "Verified sources:"
    ]

    for number, citation in (
        citation_map.items()
    ):
        lines.append(
            f"[{number}] {citation}"
        )

    return "\n".join(
        lines
    )


# ============================================================
# Final citation formatter
# ============================================================

def format_answer_with_citations(
    answer: str,
    documents: List[Document],
) -> str:
    """
    Validate LLM evidence references and append a
    deterministic verified-source section.

    Invalid evidence references are removed from the
    answer so the final response cannot point to a
    nonexistent retrieved document.
    """

    if not isinstance(
        answer,
        str,
    ):
        raise TypeError(
            "answer must be a string"
        )

    answer = answer.strip()

    if not answer:
        return ""

    citation_map = (
        build_citation_map(
            documents
        )
    )

    validation = validate_citations(
        answer,
        citation_map,
    )

    # --------------------------------------------------------
    # Remove invalid [N] / [Evidence N] references.
    # --------------------------------------------------------

    invalid_numbers = set(
        validation[
            "invalid_evidence_numbers"
        ]
    )

    cleaned_answer = answer

    for number in invalid_numbers:

        cleaned_answer = re.sub(
            rf"\[\s*Evidence\s+{number}\s*\]",
            "",
            cleaned_answer,
            flags=re.IGNORECASE,
        )

        cleaned_answer = re.sub(
            rf"\[\s*{number}\s*\]",
            "",
            cleaned_answer,
        )

    cleaned_answer = re.sub(
        r"[ \t]{2,}",
        " ",
        cleaned_answer,
    )

    cleaned_answer = re.sub(
        r"\n{3,}",
        "\n\n",
        cleaned_answer,
    ).strip()

    # --------------------------------------------------------
    # Deterministic source block.
    # --------------------------------------------------------

    source_block = (
        build_citation_block(
            documents
        )
    )

    if source_block:
        return (
            f"{cleaned_answer}\n\n"
            f"{source_block}"
        )

    return cleaned_answer


# ============================================================
# Citation lookup
# ============================================================

def get_citations(
    documents: List[Document],
) -> List[str]:
    """
    Return unique verified citations in retrieval order.
    """

    citations = []

    seen = set()

    for document in documents:

        citation = (
            get_document_citation(
                document
            )
        )

        if not citation:
            continue

        if citation in seen:
            continue

        seen.add(
            citation
        )

        citations.append(
            citation
        )

    return citations