import re
from typing import List

from langchain_core.documents import Document


def normalize_markdown(text: str) -> str:
    """Normalize Markdown generated by PyMuPDF4LLM."""

    if not isinstance(text, str):
        raise TypeError("text must be a string")

    if not text.strip():
        return ""

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    text = re.sub(
        r"[ \t]+$",
        "",
        text,
        flags=re.MULTILINE,
    )

    text = re.sub(
        r"^(#{1,6})[ \t]+",
        r"\1 ",
        text,
        flags=re.MULTILINE,
    )

    text = re.sub(
        r"^[ \t]*[•●▪◦]\s+",
        "- ",
        text,
        flags=re.MULTILINE,
    )

    text = re.sub(
        r"^(\d+)[.)][ \t]+",
        r"\1. ",
        text,
        flags=re.MULTILINE,
    )

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


def convert_documents_to_markdown(
    documents: List[Document],
) -> List[Document]:
    """Normalize Markdown and preserve metadata."""

    converted = []

    for document in documents:

        markdown = normalize_markdown(
            document.page_content
        )

        if not markdown:
            continue

        converted.append(
            Document(
                page_content=markdown,
                metadata=document.metadata.copy(),
            )
        )

    return converted